services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/home/work
      - ./data:/home/data
    command: jupyter lab --ip=0.0.0.0 --port=8080 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''
